---
# Use the VxRail API to get cluster status
 -  name: "Add Node to Cluster"
    dellemc.vxrail.vx_addnode:
      vcadmin: "{{ vcadmin }}"
      vcpasswd: "{{ vcpasswd }}"
      ip: "{{ vxm }}"
      esxhost: "{{ esxhost }}"
      vxuser: "{{ vxadmin }}"
      vxpasswd: "{{ vxpasswd }}"
      esx_mgt: "{{ esx_mgt }}"
      esx_vsan: "{{ esx_vsan }}"
      esx_vmotion: "{{ esx_vmotion }}"
      root_passwd: "{{ root_passwd }}"
    register: output

 - debug:
     msg: "{{ output }}"
